### ISSUE TITLE
Proposal: Use Next.js for the frontend 

### ISSUE THREAD

**Issue by valentinmadrid** [PrestigeDAO/web3-resume-ui#2]
I propose using Next.js as the framework of the Resume Ui frontend and Tailwind CSS for the styling side.
Here is the base routing structure I propose:
```
pages
├── index.tsx (Landing Page)
├── profiles
    └── [user_id].tsx (Resume UI)
├──  profile.tsx (Manage your own Profile)
├── governance.tsx (Integrate Governance with Governance IDL)
├── settings.tsx (User Settings Page)
```

We could then move on to the development once we have a Figma Design ready. What do you think of this?
Can I attach a PR with a base Next App to this Issue ?

**Comment by cdhiraj40** [comment]
> I propose using Next.js as the framework of the Resume Ui frontend and Tailwind CSS for the styling side. Here is the base routing structure I propose:
> 
> ```
> pages
> ├── index.tsx (Landing Page)
> ├── profiles
>     └── [user_id].tsx (Resume UI)
> ├──  profile.tsx (Manage your own Profile)
> ├── governance.tsx (Integrate Governance with Governance IDL)
> ├── settings.tsx (User Settings Page)
> ```
> 
> We could then move on to the development once we have a Figma Design ready. What do you think of this? Can I attach a PR with a base Next App to this Issue ?

This does look good with the information we have. Also, I think you should use [dapp-scaffold](https://github.com/solana-labs/dapp-scaffold) which uses Next.js + Tailwind CSS + Daisy UI for components.

**Comment by valentinmadrid** [comment]
> > I propose using Next.js as the framework of the Resume Ui frontend and Tailwind CSS for the styling side. Here is the base routing structure I propose:
> > ```
> > pages
> > ├── index.tsx (Landing Page)
> > ├── profiles
> >     └── [user_id].tsx (Resume UI)
> > ├──  profile.tsx (Manage your own Profile)
> > ├── governance.tsx (Integrate Governance with Governance IDL)
> > ├── settings.tsx (User Settings Page)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We could then move on to the development once we have a Figma Design ready. What do you think of this? Can I attach a PR with a base Next App to this Issue ?
> 
> This does look good with the information we have. Also, I think you should use [solana-dapp-scaffold](https://github.com/solana-labs/dapp-scaffold) which uses Next.js + Tailwind CSS + Daisy UI for components.

I prefer building the app from scratch, but let's discuss that on discord!

**Comment by jim4067** [comment]
hello 👋🏾 @valentinmadrid 

I think we can mark this issue as complete.
